config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def create
    @article = Article.new(article_params)
    @article.save!
    redirect_to articles_path
  end

  def new
    @article = Article.new
  end

  def edit

  end

  def show
    @id = params[:id]
    @article = Article.find(@id)
  end

  def update
  end

  def destroy
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<div class="container mt-5 ">
  <h1 class="text-primary pb-3 mb-3 border-bottom">Articles homepage</h1>
    <% @articles.each do |article| %>
    <h3><%= link_to article.title, article_path(article) %> </h3>
    <p class="text-secondary"><%= article.title %> </p>
  <% end %>
</div>

app/views/articles/new.html.erb
<div class="container mt-5 ">
    <%= form_for(@article, html: {class: "form-horizontal center"}) do |f| %>
      <div class="form-group">
        <%= f.label :title, "Title:", class: "col-md-12 control-label" %>
        <div class="col-md-12">
            <%= f.text_field :title, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :content, "Content", class: "col-md-12 control-label" %>
        <div class="col-md-12">
          <%= f.text_area :content, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.submit "Submit", class: "btn btn-primary ml-3" %>
      </div>
      <% end %>
</div>

app/views/articles/show.html.erb
<div class="container mt-5 ">
    <h3 class="text-primary pb-3 mb-3 border-bottom"><%= @article.title %> </h3>
    <p class="text-secondary"><%= @article.content %> </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<nav class="navbar navbar-light bg-light">
  <%= link_to 'Wikinimous by Ieva', articles_path, class:"navbar-brand ml-2 text-secondary"   %>
  <%= link_to 'New Article', new_article_path, class:"navbar-brand ml-2 text-secondary smaller-nav"   %>
</nav>
    <%= yield %>
  </body>
</html>